### ISSUE TITLE
Inconsistência no nome da editora, na interface "backoffice"

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielobooks#47]
Quando o nome de uma editora é alterado, a alteração não é refletida na lista de livros do backoffice, apenas nos detalhes do livro.

A inconsistência ocorre pois os dados são mantidos em 2 sistemas de banco de dados distintos.

**Comment by amandasramalho** [comment]
Caso 1 - Editora Fap-Unifesp
No backoffice existem 2 cadastros: "FapUNIFESP" e "Fap-Unifesp". O correto é "Editora Fap-Unifesp".
Todos os livros que haviam sido cadastrados como "FapUNIFESP" foram alterados para "Fap-Unifesp". No site final esta alteração aparece, porém no backoffice, continuam errado.

Caso 2 - Sociedade Brasileira de Zoologia
No backoffice o nome foi registrado como "Sociedade brasileira de zoologia", porém as iniciais devem estar em maiúsculas: "Sociedade Brasileira de Zoologia".

**Comment by fabiobatalha** [comment]
@amandasramalho 

No primeiro caso deve ser excluído o cadastro FapUNIFESP?

**Comment by amandasramalho** [comment]
@fabiobatalha 

Sim. Apenas o nome da editora. Os títulos devem constar como "Editora Fap-Unifesp".

**Comment by fabiobatalha** [comment]
Solucionado o problema nos registros da base de dados.
